app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class SearchForm(FlaskForm):
    class Meta:
        csrf = False # disable CSRF protection
    pokemon_name = StringField('Pokemon name', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import Config
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate



# init Login Manager
login = LoginManager()
login.login_view = 'auth.login'
login.login_message = 'Please log in to view the page'
login.login_message_category = 'warning'
#init database
db = SQLAlchemy()
#init Migrate
migrate = Migrate()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    login.init_app(app)
    db.init_app(app)
    migrate.init_app(app,db)

    from .blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from .blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    return app

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main',__name__,url_prefix='')

from .import routes

app/blueprints/main/routes.py
from flask import render_template, flash
import requests
from .forms import SearchForm
from flask_login import login_required
from .import bp as main

@main.route('/', methods=['GET'])
@login_required
def index():
    return render_template('index.html.j2')

@main.route('/pokemon', methods=['GET','POST'])
@login_required
def pokemon():
    pokemon_name = None
    form = SearchForm()
    # Validate Form
    if form.validate_on_submit():
        pokemon_name = form.pokemon_name.data.lower()
        form.pokemon_name.data = '' #clear form after hitting search
        url = f'https://pokeapi.co/api/v2/pokemon/{pokemon_name}'
        response = requests.get(url)
        if response.ok:
            data = response.json()
            if not data:
                flash("Something went wrong. Couldn't connect the library.",'danger')
                return render_template("pokemon.html.j2", form=form)
            
            pokemon_dict = {
                'pokemon_image': data['sprites']['other']['dream_world']['front_default'],
                'pokemon_name': data['name'],
                'ability_name': data['abilities'][0]['ability']['name'],
                'base_experience': data['base_experience'],
                'sprite_ULR': data['sprites']['front_shiny']
                }
            return render_template("pokemon.html.j2", form=form, pokemon = pokemon_dict)
        flash(f'There is no pokemon named {pokemon_name}','warning')
        return render_template("pokemon.html.j2", form=form)
    return render_template('pokemon.html.j2', form=form)
    

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
      {% block title %}
      {% endblock %}
    </title>

    <link rel="stylesheet" href="{{url_for('static',filename='css/themify-icons.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/feather.css')}}">

    <!-- fav icons -->
    <link rel="shortcut icon" href="{{url_for('static',filename='images/favicon.ico')}}" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static',filename='images/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static',filename='images/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static',filename='images/favicon-16x16.png')}}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Custom Stylesheet -->
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
    
    
    {% block css %}

    {% endblock %}
    
  </head>

  <body class="color-theme-blue mont-font">
    <div class="preloader"></div>
    <!-- Document Wrapper
	  ============================================= -->
    
      <!-- {% include './includes/nav.html' %} -->
      <!-- Navbar -->
        <!-- Nav top -->
      <div class="nav-header bg-white shadow-xs border-0">

        <div class="nav-top">
          <a href="{{url_for('main.index')}}"><span class="d-inline-block fredoka-font ls-3 fw-600 text-current font-xxl logo-text mb-0">friendbook </span> </a>
          <a href="{{url_for('main.index')}}" class="mob-menu ms-auto me-2 avatar-active-btn"><img src="https://avatars.dicebear.com/api/bottts/{{current_user.icon}}.svg" alt="user" class="w40 mt--1"></a>
         
        </div>

        <a href="#" class="p-2 text-center ms-auto menu-icon" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="dot-count bg-warning"></span><i class="feather-bell font-xl text-current"></i></a>

        <!-- Settings button -->
        <div class="p-2 ms-3 position-relative dropdown-menu-icon menu-icon cursor-pointer">
          <i class="feather-settings animation-spin d-inline-block font-xl text-current"></i>
          <div class="dropdown-menu-settings switchcolor-wrap">
              <h4 class="fw-700 font-sm mb-4">Settings</h4>
              <div class="card bg-transparent-card border-0 d-block mt-3">
                <a href="{{url_for('main.index')}}"><h4 class="d-inline font-xssss mont-font fw-700">Homepage</h4></a>
              </div>
              
              <div class="card bg-transparent-card border-0 mt-3 d-block">
                <a href="{{url_for('main.pokemon')}}"><h4 class="d-inline font-xssss mont-font fw-700">Pokemon</h4></a>
              </div>

              <div class="card bg-transparent-card border-0 d-block mt-3">
                <a href="{{url_for('auth.edit_profile')}}"><h4 class="d-inline font-xssss mont-font fw-700">Edit Profile</h4></a>
              </div>

              <div class="card bg-transparent-card border-0 d-block mt-3">
                <a href="{{url_for('auth.login')}}"><h4 class="d-inline font-xssss mont-font fw-700">Logout</h4></a>
              </div>
              
          </div>
        </div>
        
        <!-- Avatar -->
        <a href="{{url_for('main.index')}}" class="p-0 ms-3 menu-icon">
          <img src="https://avatars.dicebear.com/api/bottts/{{current_user.icon}}.svg" alt="user" class="w40 mt--1">
        </a>
      
      </div> <!-- end nav top -->

      <!-- Nav left -->
      {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        {% for class, message in messages %}
        <div class="alert alert-{{class}} alert-dismissible fade show" role='alert'>
          {{message}}
          <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
        </div>
        {% endfor %}
      {% endif %}
      {% endwith %}
      
    <div class="main-wrapper">
      {% block content%}

      {% endblock %}
      

    </div> <!-- #wrapper end -->

    



    <!-- Java scipts -->
    <script src="{{url_for('static',filename='js/plugin.js')}}"></script>
    <script src="{{url_for('static',filename='js/scripts.js')}}"></script>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><img src="{{url_for('static',filename='images/logo.png')}}" style="height:30px;"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('main.index')}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{{url_for('main.pokemon')}}">Pokemon</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
        </li>
        {% endif %}
      </ul>

      {% if current_user.is_authenticated %}
      <ul class="navbar-nav ms-auto">
          <img src="https://avatars.dicebear.com/api/bottts/{{current_user.icon}}.svg" style="height:50px">
          <li class="nav-item">
              <div class="row">
                  <div class="col-12">
                      <a class="nav-link" aria-current="page" href="{{url_for('auth.logout')}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                          <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                      </svg>
                      </a>
                  </div>
                  <div class="col-12">
                      <a class="nav-link" aria-current="page" href="{{url_for('auth.edit_profile')}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                          <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                          <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                      </svg>
                      </a>
                  </div>
              </div>  
          </li>

      </ul>
      {% endif %}
      
    </div>
  </div>
</nav>

app/templates/index.html.j2
{% extends 'base.html' %}

{% block title %}
Homepage
{% endblock %}

{% block css %}
 
{% endblock %}

{% block content %}
	<!-- Main content
	============================================= -->
	<div class="main-content bg-lightblue theme-dark-bg right-chat-active">
        <div class="middle-sidebar-bottom">
            <div class="middle-sidebar-left">
                <div class="middle-wrap">
                    <div class="card w-100 border-0 bg-white shadow-xs p-0 mb-4">
                        <div class="card-body p-lg-5 p-4 w-100 border-0">
                            <div class="row">
                                <div class="col-lg-12">
                                    <h1>Hello {{current_user.first_name}}! Welcome to <span class="d-inline-block fredoka-font ls-3 fw-600 text-current mb-0">friendbook </span>!</h1><br>
                                    Share what you are thinking with us... 
                                    <div class="text-center mb-3">
                                        <img src="{{url_for('static',filename='images/welcome.png')}}" class="img-responsive w-100">
						            </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    	<div class="card w-100 shadow-xss rounded-xxl border-0 ps-4 pt-4 pe-4 pb-3 mb-3 mt-3">
                        
                            <div class="card-body p-0">
                                <a href="#" class=" font-xssss fw-600 text-grey-500 card-body p-0 d-flex align-items-center"><i class="btn-round-sm font-xs text-primary feather-edit-3 me-2 bg-greylight"></i>Create Post</a>
                            </div>

                            <div class="card-body p-0 mt-3 position-relative">
                                <figure class="avatar position-absolute ms-2 mt-1 top-5"><img src="https://avatars.dicebear.com/api/bottts/{{current_user.icon}}.svg" alt="image" class="shadow-sm rounded-circle w30"></figure>
                                <textarea name="message" class="h100 bor-0 w-100 rounded-xxl p-2 ps-5 font-xssss text-grey-500 fw-500 border-light-md theme-dark-bg" cols="30" rows="10" placeholder="What's on your mind?"></textarea>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
		


	</div><!-- #main content end -->

{% endblock %}

app/templates/landing.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {% endblock %}
    </title>

    <link rel="stylesheet" href="{{url_for('static',filename='css/themify-icons.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/feather.css')}}">
    <!-- Favicon icon -->
    <link rel="shortcut icon" href="{{url_for('static',filename='images/favicon.ico')}}" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static',filename='images/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static',filename='images/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static',filename='images/favicon-16x16.png')}}">

    <!-- Custom Stylesheet -->
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    {% block css %}

    {% endblock %}
    
    

  </head>

  <body class="color-theme-blue mont-font">
    <div class="preloader"></div>

    <div class="main-wrap">
      <!-- Nav Bar -->
        <div class="nav-header sticky-top bg-transparent shadow-none border-0">
            <div class="nav-top w-100">
                <span class="d-inline-block fredoka-font ls-3 fw-600 text-current font-xxl logo-text mb-0">friendbook </span>

                <a href="{{url_for('auth.login')}}" class="header-btn d-none d-lg-block bg-dark fw-500 text-white font-xsss p-3 ms-auto w100 text-center lh-20 rounded-xl">Login</a>

                <a href="{{url_for('auth.register')}}" class="header-btn d-none d-lg-block bg-current fw-500 text-white font-xsss p-3 ms-2 w100 text-center lh-20 rounded-xl">Register</a>
            </div>
        </div>

      {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        {% for class, message in messages %}
        <div class="alert alert-{{class}} alert-dismissible fade show" role='alert'>
          {{message}}
          <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
        </div>
        {% endfor %}
      {% endif %}
      {% endwith %}

        <div>
          {% block content%}
          
          {% endblock %}
      </div>

    </div> <!-- end wrapper -->

  
    <!-- Optional JavaScript; choose one of the two! -->
    
    <script src="{{url_for('static',filename='js/plugin.js')}}"></script>
    <script src="{{url_for('static',filename='js/scripts.js')}}"></script>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/templates/pokemon.html.j2
{% extends 'base.html' %}
{% block title %}
Pokemon Lookup
{% endblock %}

{% block content %}
<!-- Main content
============================================= -->
<div class="main-content theme-dark-bg right-chat-active">
    <div class="text-center">
    <img src="{{url_for('static',filename='images/Pokemon-logo.jpg')}}" alt="pokemon logo">
    </div>

    <form action="{{url_for('main.pokemon')}}" method="POST">
        {{ form.hidden_tag() }}
        {{form.pokemon_name.label(class="form-label")}}
        {# searching section #}
        {{form.pokemon_name(class="form-control")}}
        {# submit button #}
        {{form.submit(class="btn btn-primary")}}
    </form>
        {% if pokemon %}
            <div class="container row row-cols-2 pt-5">
                <div class="col-3 text-center">
                    <img src={{pokemon['pokemon_image']}} class="img-fluid rounded mx-auto d-block" alt="pokemon image">
                </div>

                <div class="table-wrapper col-9 table-responsive pr-0">
                    <table class="table table-striped table-hover" style="width:100%">
                        <tr>
                            <th scope="row">Pokemon Name</th>
                            <th scope="col">{{pokemon['pokemon_name']}}</th>
                        </tr>
                        
                        <tr>
                            <th scope="row">Ability</th>
                            <td>{{pokemon['ability_name']}}</td>
                        </tr>
                        
                        <tr>
                            <th scope="row">Base Experience</th>
                            <td>{{pokemon['base_experience']}}</td>
                        </tr>
                        
                        <tr>
                            <th scope="row">Sprite URL</th>
                            <td><a href={{pokemon['sprite_ULR']}}>{{pokemon['sprite_ULR']}} </a></td>
                        </tr>
                    </table>
                </div>
            </div>
    {% endif %}
</div>

{% endblock %}


{#
  <div class="mb-3">
    <label for="pokemon" class="form-label">Pokemon name</label>
    <input type="text" name = "pokemon" class="form-control" id="pokemon">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button> #}